global using Microsoft.AspNetCore.Http;
global using Tiveriad.Repositories;
global using Tiveriad.Documents.Apis.Contracts.DocumentCategoryContracts;
global using Tiveriad.Documents.Apis.Contracts.DocumentDescriptionContracts;
global using Tiveriad.Documents.Applications.Commands.DocumentCategoryCommands;
global using Tiveriad.Documents.Applications.Commands.DocumentDescriptionCommands;
global using Tiveriad.Documents.Applications.Queries.DocumentCategoryQueries;
global using Tiveriad.Documents.Applications.Queries.DocumentDescriptionQueries;
global using Tiveriad.Documents.Core.Entities;
