name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test Tiveriad.IdGenerator.Tests
      run: dotnet test ~/Tests/Tiveriad.IdGenerator.Tests/bin/net6.0/Tiveriad.IdGenerator.Tests.dll --no-build --no-restore --verbosity detailed
    - name: Test Tiveriad.Repositories.EntityFrameworkCore.Tests
      run: dotnet test ~/Tests/Tiveriad.Repositories.EntityFrameworkCore.Tests/bin/net6.0/Tiveriad.Repositories.EntityFrameworkCore.Tests.dll --no-build --no-restore --verbosity detailed
